### PR TITLE
[handler-flowdock.rb] Add inbox support, tags variables JsonConfig param

### PR DESCRIPTION
**Pull request by talset**
Add :
- Update README
- Param -j JsonConfig : To be able to chose config name
- Change "data" format : To add client name and check name
- Function build_tag_list : To allow you to change tag by updating flowdock.json into sensu
- Push type inbox

### CODE REVIEW

**Comment by talset** [comment]
I haven't changed the "version" of the sensu-plugins-flowdock.

**Comment by mattyjones** [comment]
@talset  Can you update the CHANGELOG and we can merge/build this..  Thanks!

**Comment by talset** [comment]
@mattyjones Done. thanks.

**Comment by talset** [comment]
Version is now updated to 0.1.2

**Pull request merged**
